name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: '17'
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Check outputs
      run: echo ${{ steps.vars.outputs.sha_short }}
    - name: Build with Maven
      run: mvn clean package -DSHA=${{ steps.vars.outputs.sha_short }}
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: PandaEntus Artifacts
        path: target/PandaEntus-*.jar
