name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        distribution: 'adopt'
        java-version: '16'
    - name: Build with Maven
      run: mvn clean package
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist-without-markdown
        path: |
          target/PandaEntus-*.jar
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: |
          target/PandaEntus-*.jar
