name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        distribution: 'adopt'
        java-version: '16'
    - name: Build with Maven
      run: mvn clean package
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: PandaEntus Artifacts
        path: target/PandaEntus-*.jar
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
    - name: Get commit summary
      id: get_commit_summary
      run: |
        PREVIOUS_TAG=$(git tag --sort=-creatordate | sed -n 2p)
        echo "PREVIOUS_TAG: $PREVIOUS_TAG"
        COMMIT_SUMMARY="$(git log --oneline --pretty=tformat:"%h %s" $PREVIOUS_TAG..${{ github.ref }})"
        COMMIT_SUMMARY="${COMMIT_SUMMARY//$'\n'/'%0A'}"
        echo ::set-output name=COMMIT_SUMMARY::$COMMIT_SUMMARY
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
    - name: Upload Release Asset - Jar
      id: upload-release-asset-jar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/PandaEntus-1.3.jar
        asset_name: PandaEntus-1.3.jar
        asset_content_type: application/java-archive
    - name: Upload Release Asset - Jar With Dependencies
      id: upload-release-asset-jar-with-dependencies
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/PandaEntus-1.3-jar-with-dependencies.jar
        asset_name: PandaEntus-1.3-jar-with-dependencies.jar
        asset_content_type: application/java-archive
