name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        distribution: 'adopt'
        java-version: '16'
    - name: Build with Maven
      run: mvn clean package
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: target/PandaEntus-1.3-jar-with-dependencies.jar
