name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        distribution: 'adopt'
        java-version: '16'
    - name: Build with Maven
      run: mvn clean package
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: PandaEntus Artifacts
        path: target/PandaEntus-*.jar
    - name: Get Hash
      id: hash
      run: echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_HASH
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "$GITHUB_HASH"
        release_name: "Release $GITHUB_HASH"
        draft: false
        prerelease: false
    - name: Upload Release Asset - Jar
      id: upload-release-asset-jar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/PandaEntus-1.3.jar
        asset_name: PandaEntus-1.3.jar
        asset_content_type: application/java-archive
    - name: Upload Release Asset - Jar With Dependencies
      id: upload-release-asset-jar-with-dependencies
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/PandaEntus-1.3-jar-with-dependencies.jar
        asset_name: PandaEntus-1.3-jar-with-dependencies.jar
        asset_content_type: application/java-archive
