name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'
          cache: 'maven'
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}
      - name: Build with Maven
        run: mvn clean package -DSHA=${{ steps.vars.outputs.sha_short }} -Dbuild.type=github -Dbuild.number=${{ github.run_number }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Module Artifacts
          path: "target/**.jar"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ github.run_number }}"
          release_name: "v${{ github.run_number }}"
          draft: false
          prerelease: true
      - name: Upload Release Asset - PandaEntus-1.3.jar
        id: upload-release-asset-jar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/PandaEntus-1.3.jar
          asset_name: PandaEntus-1.3.jar
          asset_content_type: application/java-archive
      - name: Upload Release Asset - PandaEntus-1.3-jar-with-dependencies.jar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/PandaEntus-1.3-jar-with-dependencies.jar
          asset_name: PandaEntus-1.3-jar-with-dependencies.jar
          asset_content_type: application/java-archive
      - name: Check Hash
        id: md5
        run: |
          set -x
          export PANDAENTUS=$(md5sum ./target/PandaEntus-1.3.jar | cut -d ' ' -f 1)
          export PANDAENTUS_WITH_DEPENDENCIES=$(md5sum ./target/PandaEntus-1.3-jar-with-dependencies.jar | cut -d ' ' -f 1)
          echo ::set-output name=pandaentus::"$PANDAENTUS"
          echo ::set-output name=pandaentus_with_dependencies::"$PANDAENTUS_WITH_DEPENDENCIES"
          set +x
      - name: Update Release
        uses: irongut/EditRelease@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          id: ${{ steps.create_release.outputs.id }}
          body: |
            | Filename  | MD5 Hash |
            | ------------- | ------------- |
            | [PandaEntus-1.3.jar](https://github.com/SimplyRin/PandaEntus/releases/download/v${{ github.run_number }}/PandaEntus-1.3.jar)  | ${{ steps.md5.outputs.pandaentus }} |
            | [PandaEntus-1.3-jar-with-dependencies.jar](https://github.com/PandaEntus/BungeeCord/releases/download/v${{ github.run_number }}/PandaEntus-1.3-jar-with-dependencies.jar)  | ${{ steps.md5.outputs.pandaentus_with_dependencies }} |
